### ISSUE TITLE
How is this vm so much faster than the regular go randomx?

### ISSUE THREAD

**Issue by 0xffffa** [core-coin/RandomY#12]
When using this RandomY implementaton versus the original RandomX, RandomY's InitDataset function is MUCH faster. How can I achieve this on RandomX?

Particularly the InitDataset function which seems to take the longest when using random-x bindings, how is the performance improved this much? After this process the random-x bindings seem to actually work faster than xmrig however the InitDataset is costly since it takes 10+ seconds to load

**Comment by rastislavcore** [comment]
We have implemented performance profile tailored for IoT devices, incorporating both reductions and optimizations. However, the effectiveness of these adjustments may vary based on the specific hardware in use. To facilitate a more detailed analysis, please consider sharing information about your environment. This matter is not classified as an issue, but you are welcome to initiate a discussion here: https://github.com/catchthatrabbit/coreminer/discussions
